/* Cspell:disable */
import type { CountryCityMetadata, ISOCode } from "./types.js";

type MapCountryCode = Uppercase<ISOCode>;

const DEFAULT_SOURCE =
  "Capitals from worldcities 0.1.8; largest cities from SimpleMaps via world-cities-json 1.0.1";

const countryCityMetadata = {
  FJ: {
    countryCode: "FJ",
    capitalCity: "Suva",
    largestCity: "Suva",
    source: DEFAULT_SOURCE,
  },
  TZ: {
    countryCode: "TZ",
    capitalCity: "Dodoma",
    largestCity: "Dar es Salaam",
    source: DEFAULT_SOURCE,
  },
  EH: {
    countryCode: "EH",
    capitalCity: "Laayoune",
    largestCity: "Laayoune",
    source: "Manual project override for Western Sahara map code",
  },
  CA: {
    countryCode: "CA",
    capitalCity: "Ottawa",
    largestCity: "Toronto",
    source: DEFAULT_SOURCE,
  },
  US: {
    countryCode: "US",
    capitalCity: "Washington, DC",
    largestCity: "New York City",
    source: DEFAULT_SOURCE,
  },
  KZ: {
    countryCode: "KZ",
    capitalCity: "Astana",
    largestCity: "Almaty",
    source: DEFAULT_SOURCE,
  },
  UZ: {
    countryCode: "UZ",
    capitalCity: "Tashkent",
    largestCity: "Tashkent",
    source: DEFAULT_SOURCE,
  },
  PG: {
    countryCode: "PG",
    capitalCity: "Port Moresby",
    largestCity: "Port Moresby",
    source: DEFAULT_SOURCE,
  },
  ID: {
    countryCode: "ID",
    capitalCity: "Jakarta",
    largestCity: "Jakarta",
    source: DEFAULT_SOURCE,
  },
  AR: {
    countryCode: "AR",
    capitalCity: "Buenos Aires",
    largestCity: "Buenos Aires",
    source: DEFAULT_SOURCE,
  },
  CL: {
    countryCode: "CL",
    capitalCity: "Santiago",
    largestCity: "Santiago",
    source: DEFAULT_SOURCE,
  },
  CD: {
    countryCode: "CD",
    capitalCity: "Kinshasa",
    largestCity: "Kinshasa",
    source: DEFAULT_SOURCE,
  },
  SO: {
    countryCode: "SO",
    capitalCity: "Mogadishu",
    largestCity: "Mogadishu",
    source: DEFAULT_SOURCE,
  },
  KE: {
    countryCode: "KE",
    capitalCity: "Nairobi",
    largestCity: "Nairobi",
    source: DEFAULT_SOURCE,
  },
  SD: {
    countryCode: "SD",
    capitalCity: "Khartoum",
    largestCity: "Khartoum",
    source: DEFAULT_SOURCE,
  },
  TD: {
    countryCode: "TD",
    capitalCity: "N'Djamena",
    largestCity: "N'Djamena",
    source: DEFAULT_SOURCE,
  },
  HT: {
    countryCode: "HT",
    capitalCity: "Port-au-Prince",
    largestCity: "Port-au-Prince",
    source: DEFAULT_SOURCE,
  },
  DO: {
    countryCode: "DO",
    capitalCity: "Santo Domingo",
    largestCity: "Santo Domingo",
    source: DEFAULT_SOURCE,
  },
  RU: {
    countryCode: "RU",
    capitalCity: "Moscow",
    largestCity: "Moscow",
    source: DEFAULT_SOURCE,
  },
  BS: {
    countryCode: "BS",
    capitalCity: "Nassau",
    largestCity: "Nassau",
    source: DEFAULT_SOURCE,
  },
  FK: {
    countryCode: "FK",
    capitalCity: "Stanley",
    largestCity: "Stanley",
    source: DEFAULT_SOURCE,
  },
  NO: {
    countryCode: "NO",
    capitalCity: "Oslo",
    largestCity: "Oslo",
    source: DEFAULT_SOURCE,
  },
  GL: {
    countryCode: "GL",
    capitalCity: "Nuuk",
    largestCity: "Nuuk",
    source: DEFAULT_SOURCE,
  },
  TL: {
    countryCode: "TL",
    capitalCity: "Dili",
    largestCity: "Dili",
    source: DEFAULT_SOURCE,
  },
  ZA: {
    countryCode: "ZA",
    capitalCity: "Pretoria",
    largestCity: "Johannesburg",
    source: DEFAULT_SOURCE,
  },
  LS: {
    countryCode: "LS",
    capitalCity: "Maseru",
    largestCity: "Maseru",
    source: DEFAULT_SOURCE,
  },
  MX: {
    countryCode: "MX",
    capitalCity: "Mexico City",
    largestCity: "Mexico City",
    source: DEFAULT_SOURCE,
  },
  UY: {
    countryCode: "UY",
    capitalCity: "Montevideo",
    largestCity: "Montevideo",
    source: DEFAULT_SOURCE,
  },
  BR: {
    countryCode: "BR",
    capitalCity: "Brasilia",
    largestCity: "Sao Paulo",
    source: DEFAULT_SOURCE,
  },
  BO: {
    countryCode: "BO",
    capitalCity: "Sucre",
    largestCity: "Santa Cruz",
    source: DEFAULT_SOURCE,
  },
  PE: {
    countryCode: "PE",
    capitalCity: "Lima",
    largestCity: "Lima",
    source: DEFAULT_SOURCE,
  },
  CO: {
    countryCode: "CO",
    capitalCity: "Bogota",
    largestCity: "Bogota",
    source: DEFAULT_SOURCE,
  },
  PA: {
    countryCode: "PA",
    capitalCity: "Panama City",
    largestCity: "Panama City",
    source: DEFAULT_SOURCE,
  },
  CR: {
    countryCode: "CR",
    capitalCity: "San Jose",
    largestCity: "San Jose",
    source: DEFAULT_SOURCE,
  },
  NI: {
    countryCode: "NI",
    capitalCity: "Managua",
    largestCity: "Managua",
    source: DEFAULT_SOURCE,
  },
  HN: {
    countryCode: "HN",
    capitalCity: "Tegucigalpa",
    largestCity: "Tegucigalpa",
    source: DEFAULT_SOURCE,
  },
  SV: {
    countryCode: "SV",
    capitalCity: "San Salvador",
    largestCity: "San Salvador",
    source: DEFAULT_SOURCE,
  },
  GT: {
    countryCode: "GT",
    capitalCity: "Guatemala City",
    largestCity: "Guatemala City",
    source: DEFAULT_SOURCE,
  },
  BZ: {
    countryCode: "BZ",
    capitalCity: "Belmopan",
    largestCity: "Belize City",
    source: DEFAULT_SOURCE,
  },
  VE: {
    countryCode: "VE",
    capitalCity: "Caracas",
    largestCity: "Maracaibo",
    source: DEFAULT_SOURCE,
  },
  GY: {
    countryCode: "GY",
    capitalCity: "Georgetown",
    largestCity: "Georgetown",
    source: DEFAULT_SOURCE,
  },
  SR: {
    countryCode: "SR",
    capitalCity: "Paramaribo",
    largestCity: "Paramaribo",
    source: DEFAULT_SOURCE,
  },
  FR: {
    countryCode: "FR",
    capitalCity: "Paris",
    largestCity: "Paris",
    source: DEFAULT_SOURCE,
  },
  EC: {
    countryCode: "EC",
    capitalCity: "Quito",
    largestCity: "Guayaquil",
    source: DEFAULT_SOURCE,
  },
  PR: {
    countryCode: "PR",
    capitalCity: "San Juan",
    largestCity: "San Juan",
    source: DEFAULT_SOURCE,
  },
  JM: {
    countryCode: "JM",
    capitalCity: "Kingston",
    largestCity: "Kingston",
    source: DEFAULT_SOURCE,
  },
  CU: {
    countryCode: "CU",
    capitalCity: "Havana",
    largestCity: "Havana",
    source: DEFAULT_SOURCE,
  },
  ZW: {
    countryCode: "ZW",
    capitalCity: "Harare",
    largestCity: "Harare",
    source: DEFAULT_SOURCE,
  },
  BW: {
    countryCode: "BW",
    capitalCity: "Gaborone",
    largestCity: "Gaborone",
    source: DEFAULT_SOURCE,
  },
  NA: {
    countryCode: "NA",
    capitalCity: "Windhoek",
    largestCity: "Windhoek",
    source: DEFAULT_SOURCE,
  },
  SN: {
    countryCode: "SN",
    capitalCity: "Dakar",
    largestCity: "Dakar",
    source: DEFAULT_SOURCE,
  },
  ML: {
    countryCode: "ML",
    capitalCity: "Bamako",
    largestCity: "Bamako",
    source: DEFAULT_SOURCE,
  },
  MR: {
    countryCode: "MR",
    capitalCity: "Nouakchott",
    largestCity: "Nouakchott",
    source: DEFAULT_SOURCE,
  },
  BJ: {
    countryCode: "BJ",
    capitalCity: "Porto-Novo",
    largestCity: "Cotonou",
    source: DEFAULT_SOURCE,
  },
  NE: {
    countryCode: "NE",
    capitalCity: "Niamey",
    largestCity: "Niamey",
    source: DEFAULT_SOURCE,
  },
  NG: {
    countryCode: "NG",
    capitalCity: "Abuja",
    largestCity: "Lagos",
    source: DEFAULT_SOURCE,
  },
  CM: {
    countryCode: "CM",
    capitalCity: "Yaounde",
    largestCity: "Douala",
    source: DEFAULT_SOURCE,
  },
  TG: {
    countryCode: "TG",
    capitalCity: "Lome",
    largestCity: "Lome",
    source: DEFAULT_SOURCE,
  },
  GH: {
    countryCode: "GH",
    capitalCity: "Accra",
    largestCity: "Boankra",
    source: DEFAULT_SOURCE,
  },
  CI: {
    countryCode: "CI",
    capitalCity: "Yamoussoukro",
    largestCity: "Abidjan",
    source: DEFAULT_SOURCE,
  },
  GN: {
    countryCode: "GN",
    capitalCity: "Conakry",
    largestCity: "Conakry",
    source: DEFAULT_SOURCE,
  },
  GW: {
    countryCode: "GW",
    capitalCity: "Bissau",
    largestCity: "Bissau",
    source: DEFAULT_SOURCE,
  },
  LR: {
    countryCode: "LR",
    capitalCity: "Monrovia",
    largestCity: "Monrovia",
    source: DEFAULT_SOURCE,
  },
  SL: {
    countryCode: "SL",
    capitalCity: "Freetown",
    largestCity: "Freetown",
    source: DEFAULT_SOURCE,
  },
  BF: {
    countryCode: "BF",
    capitalCity: "Ouagadougou",
    largestCity: "Ouagadougou",
    source: DEFAULT_SOURCE,
  },
  CF: {
    countryCode: "CF",
    capitalCity: "Bangui",
    largestCity: "Bangui",
    source: DEFAULT_SOURCE,
  },
  CG: {
    countryCode: "CG",
    capitalCity: "Brazzaville",
    largestCity: "Brazzaville",
    source: DEFAULT_SOURCE,
  },
  GA: {
    countryCode: "GA",
    capitalCity: "Libreville",
    largestCity: "Libreville",
    source: DEFAULT_SOURCE,
  },
  GQ: {
    countryCode: "GQ",
    capitalCity: "Malabo",
    largestCity: "Bata",
    source: DEFAULT_SOURCE,
  },
  ZM: {
    countryCode: "ZM",
    capitalCity: "Lusaka",
    largestCity: "Lusaka",
    source: DEFAULT_SOURCE,
  },
  MW: {
    countryCode: "MW",
    capitalCity: "Lilongwe",
    largestCity: "Blantyre",
    source: DEFAULT_SOURCE,
  },
  MZ: {
    countryCode: "MZ",
    capitalCity: "Maputo",
    largestCity: "Maputo",
    source: DEFAULT_SOURCE,
  },
  SZ: {
    countryCode: "SZ",
    capitalCity: "Mbabane",
    largestCity: "Manzini",
    source: DEFAULT_SOURCE,
  },
  AO: {
    countryCode: "AO",
    capitalCity: "Luanda",
    largestCity: "Luanda",
    source: DEFAULT_SOURCE,
  },
  BI: {
    countryCode: "BI",
    capitalCity: "Gitega",
    largestCity: "Bujumbura",
    source: DEFAULT_SOURCE,
  },
  IL: {
    countryCode: "IL",
    capitalCity: "Jerusalem",
    largestCity: "Tel Aviv-Yafo",
    source: DEFAULT_SOURCE,
  },
  LB: {
    countryCode: "LB",
    capitalCity: "Beirut",
    largestCity: "Tripoli",
    source: DEFAULT_SOURCE,
  },
  MG: {
    countryCode: "MG",
    capitalCity: "Antananarivo",
    largestCity: "Antananarivo",
    source: DEFAULT_SOURCE,
  },
  PS: {
    countryCode: "PS",
    capitalCity: "East Jerusalem",
    largestCity: "Gaza",
    source: "Manual project override for Palestinian Territories map code",
  },
  GM: {
    countryCode: "GM",
    capitalCity: "Banjul",
    largestCity: "Banjul",
    source: DEFAULT_SOURCE,
  },
  TN: {
    countryCode: "TN",
    capitalCity: "Tunis",
    largestCity: "Tunis",
    source: DEFAULT_SOURCE,
  },
  DZ: {
    countryCode: "DZ",
    capitalCity: "Algiers",
    largestCity: "Algiers",
    source: DEFAULT_SOURCE,
  },
  JO: {
    countryCode: "JO",
    capitalCity: "Amman",
    largestCity: "Amman",
    source: DEFAULT_SOURCE,
  },
  AE: {
    countryCode: "AE",
    capitalCity: "Abu Dhabi",
    largestCity: "Dubai",
    source: DEFAULT_SOURCE,
  },
  QA: {
    countryCode: "QA",
    capitalCity: "Doha",
    largestCity: "Doha",
    source: DEFAULT_SOURCE,
  },
  KW: {
    countryCode: "KW",
    capitalCity: "Kuwait City",
    largestCity: "Kuwait City",
    source: DEFAULT_SOURCE,
  },
  IQ: {
    countryCode: "IQ",
    capitalCity: "Baghdad",
    largestCity: "Baghdad",
    source: DEFAULT_SOURCE,
  },
  OM: {
    countryCode: "OM",
    capitalCity: "Muscat",
    largestCity: "Muscat",
    source: DEFAULT_SOURCE,
  },
  VU: {
    countryCode: "VU",
    capitalCity: "Port Vila",
    largestCity: "Port-Vila",
    source: DEFAULT_SOURCE,
  },
  KH: {
    countryCode: "KH",
    capitalCity: "Phnom Penh",
    largestCity: "Phnom Penh",
    source: DEFAULT_SOURCE,
  },
  TH: {
    countryCode: "TH",
    capitalCity: "Bangkok",
    largestCity: "Bangkok",
    source: DEFAULT_SOURCE,
  },
  LA: {
    countryCode: "LA",
    capitalCity: "Vientiane",
    largestCity: "Vientiane",
    source: DEFAULT_SOURCE,
  },
  MM: {
    countryCode: "MM",
    capitalCity: "Nay Pyi Taw",
    largestCity: "Rangoon",
    source: DEFAULT_SOURCE,
  },
  VN: {
    countryCode: "VN",
    capitalCity: "Hanoi",
    largestCity: "Ho Chi Minh City",
    source: DEFAULT_SOURCE,
  },
  KP: {
    countryCode: "KP",
    capitalCity: "Pyongyang",
    largestCity: "Pyongyang",
    source: DEFAULT_SOURCE,
  },
  KR: {
    countryCode: "KR",
    capitalCity: "Seoul",
    largestCity: "Seoul",
    source: DEFAULT_SOURCE,
  },
  MN: {
    countryCode: "MN",
    capitalCity: "Ulaanbaatar",
    largestCity: "Ulaanbaatar",
    source: DEFAULT_SOURCE,
  },
  IN: {
    countryCode: "IN",
    capitalCity: "New Delhi",
    largestCity: "Delhi",
    source: DEFAULT_SOURCE,
  },
  BD: {
    countryCode: "BD",
    capitalCity: "Dhaka",
    largestCity: "Dhaka",
    source: DEFAULT_SOURCE,
  },
  BT: {
    countryCode: "BT",
    capitalCity: "Thimphu",
    largestCity: "Thimphu",
    source: DEFAULT_SOURCE,
  },
  NP: {
    countryCode: "NP",
    capitalCity: "Kathmandu",
    largestCity: "Kathmandu",
    source: DEFAULT_SOURCE,
  },
  PK: {
    countryCode: "PK",
    capitalCity: "Islamabad",
    largestCity: "Karachi",
    source: DEFAULT_SOURCE,
  },
  AF: {
    countryCode: "AF",
    capitalCity: "Kabul",
    largestCity: "Kabul",
    source: DEFAULT_SOURCE,
  },
  TJ: {
    countryCode: "TJ",
    capitalCity: "Dushanbe",
    largestCity: "Dushanbe",
    source: DEFAULT_SOURCE,
  },
  KG: {
    countryCode: "KG",
    capitalCity: "Bishkek",
    largestCity: "Bishkek",
    source: DEFAULT_SOURCE,
  },
  TM: {
    countryCode: "TM",
    capitalCity: "Ashgabat",
    largestCity: "Ashgabat",
    source: DEFAULT_SOURCE,
  },
  IR: {
    countryCode: "IR",
    capitalCity: "Tehran",
    largestCity: "Tehran",
    source: DEFAULT_SOURCE,
  },
  SY: {
    countryCode: "SY",
    capitalCity: "Damascus",
    largestCity: "Aleppo",
    source: DEFAULT_SOURCE,
  },
  AM: {
    countryCode: "AM",
    capitalCity: "Yerevan",
    largestCity: "Yerevan",
    source: DEFAULT_SOURCE,
  },
  SE: {
    countryCode: "SE",
    capitalCity: "Stockholm",
    largestCity: "Stockholm",
    source: DEFAULT_SOURCE,
  },
  BY: {
    countryCode: "BY",
    capitalCity: "Minsk",
    largestCity: "Minsk",
    source: DEFAULT_SOURCE,
  },
  UA: {
    countryCode: "UA",
    capitalCity: "Kyiv",
    largestCity: "Kyiv",
    source: DEFAULT_SOURCE,
  },
  PL: {
    countryCode: "PL",
    capitalCity: "Warsaw",
    largestCity: "Warsaw",
    source: DEFAULT_SOURCE,
  },
  AT: {
    countryCode: "AT",
    capitalCity: "Vienna",
    largestCity: "Vienna",
    source: DEFAULT_SOURCE,
  },
  HU: {
    countryCode: "HU",
    capitalCity: "Budapest",
    largestCity: "Budapest",
    source: DEFAULT_SOURCE,
  },
  MD: {
    countryCode: "MD",
    capitalCity: "Chisinau",
    largestCity: "Chisinau",
    source: DEFAULT_SOURCE,
  },
  RO: {
    countryCode: "RO",
    capitalCity: "Bucharest",
    largestCity: "Bucharest",
    source: DEFAULT_SOURCE,
  },
  LT: {
    countryCode: "LT",
    capitalCity: "Vilnius",
    largestCity: "Vilnius",
    source: DEFAULT_SOURCE,
  },
  LV: {
    countryCode: "LV",
    capitalCity: "Riga",
    largestCity: "Riga",
    source: DEFAULT_SOURCE,
  },
  EE: {
    countryCode: "EE",
    capitalCity: "Tallinn",
    largestCity: "Tallinn",
    source: DEFAULT_SOURCE,
  },
  DE: {
    countryCode: "DE",
    capitalCity: "Berlin",
    largestCity: "Berlin",
    source: DEFAULT_SOURCE,
  },
  BG: {
    countryCode: "BG",
    capitalCity: "Sofia",
    largestCity: "Sofia",
    source: DEFAULT_SOURCE,
  },
  GR: {
    countryCode: "GR",
    capitalCity: "Athens",
    largestCity: "Athens",
    source: DEFAULT_SOURCE,
  },
  TR: {
    countryCode: "TR",
    capitalCity: "Ankara",
    largestCity: "Istanbul",
    source: DEFAULT_SOURCE,
  },
  AL: {
    countryCode: "AL",
    capitalCity: "Tirana",
    largestCity: "Tirana",
    source: DEFAULT_SOURCE,
  },
  HR: {
    countryCode: "HR",
    capitalCity: "Zagreb",
    largestCity: "Zagreb",
    source: DEFAULT_SOURCE,
  },
  CH: {
    countryCode: "CH",
    capitalCity: "Bern",
    largestCity: "Zurich",
    source: DEFAULT_SOURCE,
  },
  LU: {
    countryCode: "LU",
    capitalCity: "Luxembourg",
    largestCity: "Luxembourg",
    source: DEFAULT_SOURCE,
  },
  BE: {
    countryCode: "BE",
    capitalCity: "Brussels",
    largestCity: "Brussels",
    source: DEFAULT_SOURCE,
  },
  NL: {
    countryCode: "NL",
    capitalCity: "Amsterdam",
    largestCity: "Amsterdam",
    source: DEFAULT_SOURCE,
  },
  PT: {
    countryCode: "PT",
    capitalCity: "Lisbon",
    largestCity: "Lisbon",
    source: DEFAULT_SOURCE,
  },
  ES: {
    countryCode: "ES",
    capitalCity: "Madrid",
    largestCity: "Madrid",
    source: DEFAULT_SOURCE,
  },
  IE: {
    countryCode: "IE",
    capitalCity: "Dublin",
    largestCity: "Dublin",
    source: DEFAULT_SOURCE,
  },
  NC: {
    countryCode: "NC",
    capitalCity: "Noumea",
    largestCity: "Noumea",
    source: DEFAULT_SOURCE,
  },
  SB: {
    countryCode: "SB",
    capitalCity: "Honiara",
    largestCity: "Honiara",
    source: DEFAULT_SOURCE,
  },
  NZ: {
    countryCode: "NZ",
    capitalCity: "Wellington",
    largestCity: "Auckland",
    source: DEFAULT_SOURCE,
  },
  AU: {
    countryCode: "AU",
    capitalCity: "Canberra",
    largestCity: "Sydney",
    source: DEFAULT_SOURCE,
  },
  LK: {
    countryCode: "LK",
    capitalCity: "Colombo",
    largestCity: "Colombo",
    source: DEFAULT_SOURCE,
  },
  CN: {
    countryCode: "CN",
    capitalCity: "Beijing",
    largestCity: "Guangzhou",
    source: DEFAULT_SOURCE,
  },
  TW: {
    countryCode: "TW",
    capitalCity: "Taipei",
    largestCity: "Taipei",
    source: DEFAULT_SOURCE,
  },
  IT: {
    countryCode: "IT",
    capitalCity: "Rome",
    largestCity: "Rome",
    source: DEFAULT_SOURCE,
  },
  DK: {
    countryCode: "DK",
    capitalCity: "Copenhagen",
    largestCity: "Copenhagen",
    source: DEFAULT_SOURCE,
  },
  GB: {
    countryCode: "GB",
    capitalCity: "London",
    largestCity: "London",
    source: DEFAULT_SOURCE,
  },
  IS: {
    countryCode: "IS",
    capitalCity: "Reykjavik",
    largestCity: "Reykjavik",
    source: DEFAULT_SOURCE,
  },
  AZ: {
    countryCode: "AZ",
    capitalCity: "Baku",
    largestCity: "Baku",
    source: DEFAULT_SOURCE,
  },
  GE: {
    countryCode: "GE",
    capitalCity: "Tbilisi",
    largestCity: "Tbilisi",
    source: DEFAULT_SOURCE,
  },
  PH: {
    countryCode: "PH",
    capitalCity: "Manila",
    largestCity: "Manila",
    source: DEFAULT_SOURCE,
  },
  MY: {
    countryCode: "MY",
    capitalCity: "Kuala Lumpur",
    largestCity: "Kuala Lumpur",
    source: DEFAULT_SOURCE,
  },
  BN: {
    countryCode: "BN",
    capitalCity: "Bandar Seri Begawan",
    largestCity: "Bandar Seri Begawan",
    source: DEFAULT_SOURCE,
  },
  SI: {
    countryCode: "SI",
    capitalCity: "Ljubljana",
    largestCity: "Ljubljana",
    source: DEFAULT_SOURCE,
  },
  FI: {
    countryCode: "FI",
    capitalCity: "Helsinki",
    largestCity: "Helsinki",
    source: DEFAULT_SOURCE,
  },
  SK: {
    countryCode: "SK",
    capitalCity: "Bratislava",
    largestCity: "Bratislava",
    source: DEFAULT_SOURCE,
  },
  CZ: {
    countryCode: "CZ",
    capitalCity: "Prague",
    largestCity: "Prague",
    source: DEFAULT_SOURCE,
  },
  ER: {
    countryCode: "ER",
    capitalCity: "Asmara",
    largestCity: "Asmara",
    source: DEFAULT_SOURCE,
  },
  JP: {
    countryCode: "JP",
    capitalCity: "Tokyo",
    largestCity: "Tokyo",
    source: DEFAULT_SOURCE,
  },
  PY: {
    countryCode: "PY",
    capitalCity: "Asuncion",
    largestCity: "Asuncion",
    source: DEFAULT_SOURCE,
  },
  YE: {
    countryCode: "YE",
    capitalCity: "Sanaa",
    largestCity: "Sanaa",
    source: DEFAULT_SOURCE,
  },
  SA: {
    countryCode: "SA",
    capitalCity: "Riyadh",
    largestCity: "Riyadh",
    source: DEFAULT_SOURCE,
  },
  CYP: {
    countryCode: "CYP",
    capitalCity: "Nicosia",
    largestCity: "Nicosia",
    source: "Manual project override for Northern Cyprus map code",
  },
  CY: {
    countryCode: "CY",
    capitalCity: "Nicosia",
    largestCity: "Nicosia",
    source: DEFAULT_SOURCE,
  },
  MA: {
    countryCode: "MA",
    capitalCity: "Rabat",
    largestCity: "Casablanca",
    source: DEFAULT_SOURCE,
  },
  EG: {
    countryCode: "EG",
    capitalCity: "Cairo",
    largestCity: "Cairo",
    source: DEFAULT_SOURCE,
  },
  LY: {
    countryCode: "LY",
    capitalCity: "Tripoli",
    largestCity: "Tripoli",
    source: DEFAULT_SOURCE,
  },
  ET: {
    countryCode: "ET",
    capitalCity: "Addis Ababa",
    largestCity: "Addis Ababa",
    source: DEFAULT_SOURCE,
  },
  DJ: {
    countryCode: "DJ",
    capitalCity: "Djibouti",
    largestCity: "Djibouti",
    source: DEFAULT_SOURCE,
  },
  SOM: {
    countryCode: "SOM",
    capitalCity: "Hargeisa",
    largestCity: "Hargeisa",
    source: "Manual project override for Somaliland map code",
  },
  UG: {
    countryCode: "UG",
    capitalCity: "Kampala",
    largestCity: "Kampala",
    source: DEFAULT_SOURCE,
  },
  RW: {
    countryCode: "RW",
    capitalCity: "Kigali",
    largestCity: "Kigali",
    source: DEFAULT_SOURCE,
  },
  BA: {
    countryCode: "BA",
    capitalCity: "Sarajevo",
    largestCity: "Sarajevo",
    source: DEFAULT_SOURCE,
  },
  MK: {
    countryCode: "MK",
    capitalCity: "Skopje",
    largestCity: "Skopje",
    source: DEFAULT_SOURCE,
  },
  RS: {
    countryCode: "RS",
    capitalCity: "Belgrade",
    largestCity: "Belgrade",
    source: DEFAULT_SOURCE,
  },
  ME: {
    countryCode: "ME",
    capitalCity: "Podgorica",
    largestCity: "Podgorica",
    source: DEFAULT_SOURCE,
  },
  XK: {
    countryCode: "XK",
    capitalCity: "Pristina",
    largestCity: "Pristina",
    source: DEFAULT_SOURCE,
  },
  TT: {
    countryCode: "TT",
    capitalCity: "Port of Spain",
    largestCity: "Chaguanas",
    source: DEFAULT_SOURCE,
  },
  SS: {
    countryCode: "SS",
    capitalCity: "Juba",
    largestCity: "Juba",
    source: DEFAULT_SOURCE,
  },
} satisfies Record<MapCountryCode, CountryCityMetadata>;

export function getCountryCityMetadata(
  countryCode: ISOCode,
): CountryCityMetadata | undefined {
  return countryCityMetadata[countryCode.toUpperCase() as MapCountryCode];
}

export { countryCityMetadata };
