/* prettier-ignore */
// AUTO-GENERATED by lib/scripts/migrate-to-topo.ts - do not edit manually.
// Compatibility module for existing imports.
// New code should import a specific country geometry tier module.

export { topologyMetadata } from "./countries-reduced.topo.js";
export { default } from "./countries-reduced.topo.js";
