/* Cspell:disable */
import type { CountryCityMetadata, ISOCode } from "./types.js";

type MapCountryCode = Uppercase<ISOCode>;

const DEFAULT_SOURCE =
  "Capital names from worldcities 0.1.8; capital coordinates from SimpleMaps via world-cities-json 1.0.1, with manual coordinates for topology-specific entities";

export const countryCityMetadata = {
  FJ: {
    countryCode: "FJ",
    capitalCity: "Suva",
    capitalLocation: [178.4419, -18.1416],
    source: DEFAULT_SOURCE,
  },
  TZ: {
    countryCode: "TZ",
    capitalCity: "Dodoma",
    capitalLocation: [35.7419, -6.1731],
    source: DEFAULT_SOURCE,
  },
  EH: {
    countryCode: "EH",
    capitalCity: "Laayoune",
    capitalLocation: [-13.2033, 27.1536],
    source: DEFAULT_SOURCE,
  },
  CA: {
    countryCode: "CA",
    capitalCity: "Ottawa",
    capitalLocation: [-75.695, 45.4247],
    source: DEFAULT_SOURCE,
  },
  US: {
    countryCode: "US",
    capitalCity: "Washington, DC",
    capitalLocation: [-77.0163, 38.9047],
    source: DEFAULT_SOURCE,
  },
  KZ: {
    countryCode: "KZ",
    capitalCity: "Astana",
    capitalLocation: [71.4333, 51.1333],
    source: DEFAULT_SOURCE,
  },
  UZ: {
    countryCode: "UZ",
    capitalCity: "Tashkent",
    capitalLocation: [69.2797, 41.3111],
    source: DEFAULT_SOURCE,
  },
  PG: {
    countryCode: "PG",
    capitalCity: "Port Moresby",
    capitalLocation: [147.1494, -9.4789],
    source: DEFAULT_SOURCE,
  },
  ID: {
    countryCode: "ID",
    capitalCity: "Jakarta",
    capitalLocation: [106.8275, -6.175],
    source: DEFAULT_SOURCE,
  },
  AR: {
    countryCode: "AR",
    capitalCity: "Buenos Aires",
    capitalLocation: [-58.3819, -34.5997],
    source: DEFAULT_SOURCE,
  },
  CL: {
    countryCode: "CL",
    capitalCity: "Santiago",
    capitalLocation: [-70.6506, -33.4372],
    source: DEFAULT_SOURCE,
  },
  CD: {
    countryCode: "CD",
    capitalCity: "Kinshasa",
    capitalLocation: [15.3222, -4.325],
    source: DEFAULT_SOURCE,
  },
  SO: {
    countryCode: "SO",
    capitalCity: "Mogadishu",
    capitalLocation: [45.3419, 2.0392],
    source: DEFAULT_SOURCE,
  },
  KE: {
    countryCode: "KE",
    capitalCity: "Nairobi",
    capitalLocation: [36.8172, -1.2864],
    source: DEFAULT_SOURCE,
  },
  SD: {
    countryCode: "SD",
    capitalCity: "Khartoum",
    capitalLocation: [32.56, 15.5006],
    source: DEFAULT_SOURCE,
  },
  TD: {
    countryCode: "TD",
    capitalCity: "N'Djamena",
    capitalLocation: [15.05, 12.11],
    source: DEFAULT_SOURCE,
  },
  HT: {
    countryCode: "HT",
    capitalCity: "Port-au-Prince",
    capitalLocation: [-72.3333, 18.5333],
    source: DEFAULT_SOURCE,
  },
  DO: {
    countryCode: "DO",
    capitalCity: "Santo Domingo",
    capitalLocation: [-69.8933, 18.4764],
    source: DEFAULT_SOURCE,
  },
  RU: {
    countryCode: "RU",
    capitalCity: "Moscow",
    capitalLocation: [37.6178, 55.7558],
    source: DEFAULT_SOURCE,
  },
  BS: {
    countryCode: "BS",
    capitalCity: "Nassau",
    capitalLocation: [-77.3386, 25.0781],
    source: DEFAULT_SOURCE,
  },
  FK: {
    countryCode: "FK",
    capitalCity: "Stanley",
    capitalLocation: [-57.85, -51.7],
    source: DEFAULT_SOURCE,
  },
  NO: {
    countryCode: "NO",
    capitalCity: "Oslo",
    capitalLocation: [10.7389, 59.9133],
    source: DEFAULT_SOURCE,
  },
  GL: {
    countryCode: "GL",
    capitalCity: "Nuuk",
    capitalLocation: [-51.6942, 64.1814],
    source: DEFAULT_SOURCE,
  },
  TL: {
    countryCode: "TL",
    capitalCity: "Dili",
    capitalLocation: [125.5783, -8.5536],
    source: DEFAULT_SOURCE,
  },
  ZA: {
    countryCode: "ZA",
    capitalCity: "Pretoria",
    capitalLocation: [28.1881, -25.7461],
    source: DEFAULT_SOURCE,
  },
  LS: {
    countryCode: "LS",
    capitalCity: "Maseru",
    capitalLocation: [27.48, -29.31],
    source: DEFAULT_SOURCE,
  },
  MX: {
    countryCode: "MX",
    capitalCity: "Mexico City",
    capitalLocation: [-99.1333, 19.4333],
    source: DEFAULT_SOURCE,
  },
  UY: {
    countryCode: "UY",
    capitalCity: "Montevideo",
    capitalLocation: [-56.1819, -34.8836],
    source: DEFAULT_SOURCE,
  },
  BR: {
    countryCode: "BR",
    capitalCity: "Brasilia",
    capitalLocation: [-47.8828, -15.7939],
    source: DEFAULT_SOURCE,
  },
  BO: {
    countryCode: "BO",
    capitalCity: "Sucre",
    capitalLocation: [-65.2592, -19.0475],
    source: DEFAULT_SOURCE,
  },
  PE: {
    countryCode: "PE",
    capitalCity: "Lima",
    capitalLocation: [-77.0375, -12.06],
    source: DEFAULT_SOURCE,
  },
  CO: {
    countryCode: "CO",
    capitalCity: "Bogota",
    capitalLocation: [-74.0722, 4.7111],
    source: DEFAULT_SOURCE,
  },
  PA: {
    countryCode: "PA",
    capitalCity: "Panama City",
    capitalLocation: [-79.5167, 8.9833],
    source: DEFAULT_SOURCE,
  },
  CR: {
    countryCode: "CR",
    capitalCity: "San Jose",
    capitalLocation: [-84.08, 9.9325],
    source: DEFAULT_SOURCE,
  },
  NI: {
    countryCode: "NI",
    capitalCity: "Managua",
    capitalLocation: [-86.2738, 12.1544],
    source: DEFAULT_SOURCE,
  },
  HN: {
    countryCode: "HN",
    capitalCity: "Tegucigalpa",
    capitalLocation: [-87.2167, 14.1],
    source: DEFAULT_SOURCE,
  },
  SV: {
    countryCode: "SV",
    capitalCity: "San Salvador",
    capitalLocation: [-89.1914, 13.6989],
    source: DEFAULT_SOURCE,
  },
  GT: {
    countryCode: "GT",
    capitalCity: "Guatemala City",
    capitalLocation: [-90.5252, 14.6099],
    source: DEFAULT_SOURCE,
  },
  BZ: {
    countryCode: "BZ",
    capitalCity: "Belmopan",
    capitalLocation: [-88.7669, 17.2514],
    source: DEFAULT_SOURCE,
  },
  VE: {
    countryCode: "VE",
    capitalCity: "Caracas",
    capitalLocation: [-66.9036, 10.4806],
    source: DEFAULT_SOURCE,
  },
  GY: {
    countryCode: "GY",
    capitalCity: "Georgetown",
    capitalLocation: [-58.1508, 6.8058],
    source: DEFAULT_SOURCE,
  },
  SR: {
    countryCode: "SR",
    capitalCity: "Paramaribo",
    capitalLocation: [-55.2039, 5.8522],
    source: DEFAULT_SOURCE,
  },
  FR: {
    countryCode: "FR",
    capitalCity: "Paris",
    capitalLocation: [2.3522, 48.8567],
    source: DEFAULT_SOURCE,
  },
  EC: {
    countryCode: "EC",
    capitalCity: "Quito",
    capitalLocation: [-78.5125, -0.22],
    source: DEFAULT_SOURCE,
  },
  PR: {
    countryCode: "PR",
    capitalCity: "San Juan",
    capitalLocation: [-66.061, 18.3985],
    source: DEFAULT_SOURCE,
  },
  JM: {
    countryCode: "JM",
    capitalCity: "Kingston",
    capitalLocation: [-76.7931, 17.9714],
    source: DEFAULT_SOURCE,
  },
  CU: {
    countryCode: "CU",
    capitalCity: "Havana",
    capitalLocation: [-82.3589, 23.1367],
    source: DEFAULT_SOURCE,
  },
  ZW: {
    countryCode: "ZW",
    capitalCity: "Harare",
    capitalLocation: [31.0522, -17.8292],
    source: DEFAULT_SOURCE,
  },
  BW: {
    countryCode: "BW",
    capitalCity: "Gaborone",
    capitalLocation: [25.9122, -24.6581],
    source: DEFAULT_SOURCE,
  },
  NA: {
    countryCode: "NA",
    capitalCity: "Windhoek",
    capitalLocation: [17.0836, -22.57],
    source: DEFAULT_SOURCE,
  },
  SN: {
    countryCode: "SN",
    capitalCity: "Dakar",
    capitalLocation: [-17.4467, 14.6928],
    source: DEFAULT_SOURCE,
  },
  ML: {
    countryCode: "ML",
    capitalCity: "Bamako",
    capitalLocation: [-7.9922, 12.6458],
    source: DEFAULT_SOURCE,
  },
  MR: {
    countryCode: "MR",
    capitalCity: "Nouakchott",
    capitalLocation: [-15.9785, 18.0858],
    source: DEFAULT_SOURCE,
  },
  BJ: {
    countryCode: "BJ",
    capitalCity: "Porto-Novo",
    capitalLocation: [2.605, 6.4972],
    source: DEFAULT_SOURCE,
  },
  NE: {
    countryCode: "NE",
    capitalCity: "Niamey",
    capitalLocation: [2.1175, 13.515],
    source: DEFAULT_SOURCE,
  },
  NG: {
    countryCode: "NG",
    capitalCity: "Abuja",
    capitalLocation: [7.4833, 9.0667],
    source: DEFAULT_SOURCE,
  },
  CM: {
    countryCode: "CM",
    capitalCity: "Yaounde",
    capitalLocation: [11.5167, 3.8667],
    source: DEFAULT_SOURCE,
  },
  TG: {
    countryCode: "TG",
    capitalCity: "Lome",
    capitalLocation: [1.2228, 6.1319],
    source: DEFAULT_SOURCE,
  },
  GH: {
    countryCode: "GH",
    capitalCity: "Accra",
    capitalLocation: [-0.2, 5.55],
    source: DEFAULT_SOURCE,
  },
  CI: {
    countryCode: "CI",
    capitalCity: "Yamoussoukro",
    capitalLocation: [-5.2767, 6.8161],
    source: DEFAULT_SOURCE,
  },
  GN: {
    countryCode: "GN",
    capitalCity: "Conakry",
    capitalLocation: [-13.7122, 9.5092],
    source: DEFAULT_SOURCE,
  },
  GW: {
    countryCode: "GW",
    capitalCity: "Bissau",
    capitalLocation: [-15.5667, 11.85],
    source: DEFAULT_SOURCE,
  },
  LR: {
    countryCode: "LR",
    capitalCity: "Monrovia",
    capitalLocation: [-10.8014, 6.3133],
    source: DEFAULT_SOURCE,
  },
  SL: {
    countryCode: "SL",
    capitalCity: "Freetown",
    capitalLocation: [-13.2344, 8.4844],
    source: DEFAULT_SOURCE,
  },
  BF: {
    countryCode: "BF",
    capitalCity: "Ouagadougou",
    capitalLocation: [-1.5275, 12.3686],
    source: DEFAULT_SOURCE,
  },
  CF: {
    countryCode: "CF",
    capitalCity: "Bangui",
    capitalLocation: [18.5628, 4.3733],
    source: DEFAULT_SOURCE,
  },
  CG: {
    countryCode: "CG",
    capitalCity: "Brazzaville",
    capitalLocation: [15.2714, -4.2694],
    source: DEFAULT_SOURCE,
  },
  GA: {
    countryCode: "GA",
    capitalCity: "Libreville",
    capitalLocation: [9.4542, 0.3903],
    source: DEFAULT_SOURCE,
  },
  GQ: {
    countryCode: "GQ",
    capitalCity: "Malabo",
    capitalLocation: [8.7833, 3.75],
    source: DEFAULT_SOURCE,
  },
  ZM: {
    countryCode: "ZM",
    capitalCity: "Lusaka",
    capitalLocation: [28.2833, -15.4167],
    source: DEFAULT_SOURCE,
  },
  MW: {
    countryCode: "MW",
    capitalCity: "Lilongwe",
    capitalLocation: [33.7833, -13.9833],
    source: DEFAULT_SOURCE,
  },
  MZ: {
    countryCode: "MZ",
    capitalCity: "Maputo",
    capitalLocation: [32.5833, -25.9667],
    source: DEFAULT_SOURCE,
  },
  SZ: {
    countryCode: "SZ",
    capitalCity: "Mbabane",
    capitalLocation: [31.1333, -26.3167],
    source: DEFAULT_SOURCE,
  },
  AO: {
    countryCode: "AO",
    capitalCity: "Luanda",
    capitalLocation: [13.2344, -8.8383],
    source: DEFAULT_SOURCE,
  },
  BI: {
    countryCode: "BI",
    capitalCity: "Gitega",
    capitalLocation: [29.925, -3.4283],
    source: DEFAULT_SOURCE,
  },
  IL: {
    countryCode: "IL",
    capitalCity: "Jerusalem",
    capitalLocation: [35.2066, 31.7784],
    source: DEFAULT_SOURCE,
  },
  LB: {
    countryCode: "LB",
    capitalCity: "Beirut",
    capitalLocation: [35.5131, 33.8869],
    source: DEFAULT_SOURCE,
  },
  MG: {
    countryCode: "MG",
    capitalCity: "Antananarivo",
    capitalLocation: [47.5167, -18.9333],
    source: DEFAULT_SOURCE,
  },
  PS: {
    countryCode: "PS",
    capitalCity: "East Jerusalem",
    capitalLocation: [35.2332, 31.7767],
    source: DEFAULT_SOURCE,
  },
  GM: {
    countryCode: "GM",
    capitalCity: "Banjul",
    capitalLocation: [-16.5775, 13.4531],
    source: DEFAULT_SOURCE,
  },
  TN: {
    countryCode: "TN",
    capitalCity: "Tunis",
    capitalLocation: [10.1817, 36.8064],
    source: DEFAULT_SOURCE,
  },
  DZ: {
    countryCode: "DZ",
    capitalCity: "Algiers",
    capitalLocation: [3.0589, 36.7539],
    source: DEFAULT_SOURCE,
  },
  JO: {
    countryCode: "JO",
    capitalCity: "Amman",
    capitalLocation: [35.9328, 31.9497],
    source: DEFAULT_SOURCE,
  },
  AE: {
    countryCode: "AE",
    capitalCity: "Abu Dhabi",
    capitalLocation: [54.3667, 24.4667],
    source: DEFAULT_SOURCE,
  },
  QA: {
    countryCode: "QA",
    capitalCity: "Doha",
    capitalLocation: [51.5333, 25.2867],
    source: DEFAULT_SOURCE,
  },
  KW: {
    countryCode: "KW",
    capitalCity: "Kuwait City",
    capitalLocation: [47.9783, 29.3697],
    source: DEFAULT_SOURCE,
  },
  IQ: {
    countryCode: "IQ",
    capitalCity: "Baghdad",
    capitalLocation: [44.3661, 33.3153],
    source: DEFAULT_SOURCE,
  },
  OM: {
    countryCode: "OM",
    capitalCity: "Muscat",
    capitalLocation: [58.5922, 23.6139],
    source: DEFAULT_SOURCE,
  },
  VU: {
    countryCode: "VU",
    capitalCity: "Port Vila",
    capitalLocation: [168.3167, -17.7333],
    source: DEFAULT_SOURCE,
  },
  KH: {
    countryCode: "KH",
    capitalCity: "Phnom Penh",
    capitalLocation: [104.9211, 11.5694],
    source: DEFAULT_SOURCE,
  },
  TH: {
    countryCode: "TH",
    capitalCity: "Bangkok",
    capitalLocation: [100.4942, 13.7525],
    source: DEFAULT_SOURCE,
  },
  LA: {
    countryCode: "LA",
    capitalCity: "Vientiane",
    capitalLocation: [102.6, 17.9667],
    source: DEFAULT_SOURCE,
  },
  MM: {
    countryCode: "MM",
    capitalCity: "Nay Pyi Taw",
    capitalLocation: [96.1167, 19.7333],
    source: DEFAULT_SOURCE,
  },
  VN: {
    countryCode: "VN",
    capitalCity: "Hanoi",
    capitalLocation: [105.8542, 21.0283],
    source: DEFAULT_SOURCE,
  },
  KP: {
    countryCode: "KP",
    capitalCity: "Pyongyang",
    capitalLocation: [125.7381, 39.0194],
    source: DEFAULT_SOURCE,
  },
  KR: {
    countryCode: "KR",
    capitalCity: "Seoul",
    capitalLocation: [126.99, 37.56],
    source: DEFAULT_SOURCE,
  },
  MN: {
    countryCode: "MN",
    capitalCity: "Ulaanbaatar",
    capitalLocation: [106.9172, 47.9203],
    source: DEFAULT_SOURCE,
  },
  IN: {
    countryCode: "IN",
    capitalCity: "New Delhi",
    capitalLocation: [77.209, 28.6139],
    source: DEFAULT_SOURCE,
  },
  BD: {
    countryCode: "BD",
    capitalCity: "Dhaka",
    capitalLocation: [90.3889, 23.7639],
    source: DEFAULT_SOURCE,
  },
  BT: {
    countryCode: "BT",
    capitalCity: "Thimphu",
    capitalLocation: [89.6361, 27.4722],
    source: DEFAULT_SOURCE,
  },
  NP: {
    countryCode: "NP",
    capitalCity: "Kathmandu",
    capitalLocation: [85.324, 27.7172],
    source: DEFAULT_SOURCE,
  },
  PK: {
    countryCode: "PK",
    capitalCity: "Islamabad",
    capitalLocation: [73.0639, 33.6931],
    source: DEFAULT_SOURCE,
  },
  AF: {
    countryCode: "AF",
    capitalCity: "Kabul",
    capitalLocation: [69.1783, 34.5253],
    source: DEFAULT_SOURCE,
  },
  TJ: {
    countryCode: "TJ",
    capitalCity: "Dushanbe",
    capitalLocation: [68.78, 38.5367],
    source: DEFAULT_SOURCE,
  },
  KG: {
    countryCode: "KG",
    capitalCity: "Bishkek",
    capitalLocation: [74.6122, 42.8747],
    source: DEFAULT_SOURCE,
  },
  TM: {
    countryCode: "TM",
    capitalCity: "Ashgabat",
    capitalLocation: [58.3833, 37.95],
    source: DEFAULT_SOURCE,
  },
  IR: {
    countryCode: "IR",
    capitalCity: "Tehran",
    capitalLocation: [51.3889, 35.6892],
    source: DEFAULT_SOURCE,
  },
  SY: {
    countryCode: "SY",
    capitalCity: "Damascus",
    capitalLocation: [36.2919, 33.5131],
    source: DEFAULT_SOURCE,
  },
  AM: {
    countryCode: "AM",
    capitalCity: "Yerevan",
    capitalLocation: [44.5144, 40.1814],
    source: DEFAULT_SOURCE,
  },
  SE: {
    countryCode: "SE",
    capitalCity: "Stockholm",
    capitalLocation: [18.0686, 59.3294],
    source: DEFAULT_SOURCE,
  },
  BY: {
    countryCode: "BY",
    capitalCity: "Minsk",
    capitalLocation: [27.5667, 53.9],
    source: DEFAULT_SOURCE,
  },
  UA: {
    countryCode: "UA",
    capitalCity: "Kyiv",
    capitalLocation: [30.5233, 50.45],
    source: DEFAULT_SOURCE,
  },
  PL: {
    countryCode: "PL",
    capitalCity: "Warsaw",
    capitalLocation: [21.0111, 52.23],
    source: DEFAULT_SOURCE,
  },
  AT: {
    countryCode: "AT",
    capitalCity: "Vienna",
    capitalLocation: [16.3725, 48.2083],
    source: DEFAULT_SOURCE,
  },
  HU: {
    countryCode: "HU",
    capitalCity: "Budapest",
    capitalLocation: [19.0514, 47.4925],
    source: DEFAULT_SOURCE,
  },
  MD: {
    countryCode: "MD",
    capitalCity: "Chisinau",
    capitalLocation: [28.8353, 47.0228],
    source: DEFAULT_SOURCE,
  },
  RO: {
    countryCode: "RO",
    capitalCity: "Bucharest",
    capitalLocation: [26.1039, 44.4325],
    source: DEFAULT_SOURCE,
  },
  LT: {
    countryCode: "LT",
    capitalCity: "Vilnius",
    capitalLocation: [25.28, 54.6872],
    source: DEFAULT_SOURCE,
  },
  LV: {
    countryCode: "LV",
    capitalCity: "Riga",
    capitalLocation: [24.1064, 56.9489],
    source: DEFAULT_SOURCE,
  },
  EE: {
    countryCode: "EE",
    capitalCity: "Tallinn",
    capitalLocation: [24.7453, 59.4372],
    source: DEFAULT_SOURCE,
  },
  DE: {
    countryCode: "DE",
    capitalCity: "Berlin",
    capitalLocation: [13.405, 52.52],
    source: DEFAULT_SOURCE,
  },
  BG: {
    countryCode: "BG",
    capitalCity: "Sofia",
    capitalLocation: [23.33, 42.7],
    source: DEFAULT_SOURCE,
  },
  GR: {
    countryCode: "GR",
    capitalCity: "Athens",
    capitalLocation: [23.7281, 37.9842],
    source: DEFAULT_SOURCE,
  },
  TR: {
    countryCode: "TR",
    capitalCity: "Ankara",
    capitalLocation: [32.85, 39.93],
    source: DEFAULT_SOURCE,
  },
  AL: {
    countryCode: "AL",
    capitalCity: "Tirana",
    capitalLocation: [19.8178, 41.3289],
    source: DEFAULT_SOURCE,
  },
  HR: {
    countryCode: "HR",
    capitalCity: "Zagreb",
    capitalLocation: [15.9833, 45.8167],
    source: DEFAULT_SOURCE,
  },
  CH: {
    countryCode: "CH",
    capitalCity: "Bern",
    capitalLocation: [7.4475, 46.9481],
    source: DEFAULT_SOURCE,
  },
  LU: {
    countryCode: "LU",
    capitalCity: "Luxembourg",
    capitalLocation: [6.1319, 49.6117],
    source: DEFAULT_SOURCE,
  },
  BE: {
    countryCode: "BE",
    capitalCity: "Brussels",
    capitalLocation: [4.3525, 50.8467],
    source: DEFAULT_SOURCE,
  },
  NL: {
    countryCode: "NL",
    capitalCity: "Amsterdam",
    capitalLocation: [4.8936, 52.3728],
    source: DEFAULT_SOURCE,
  },
  PT: {
    countryCode: "PT",
    capitalCity: "Lisbon",
    capitalLocation: [-9.15, 38.7253],
    source: DEFAULT_SOURCE,
  },
  ES: {
    countryCode: "ES",
    capitalCity: "Madrid",
    capitalLocation: [-3.7033, 40.4169],
    source: DEFAULT_SOURCE,
  },
  IE: {
    countryCode: "IE",
    capitalCity: "Dublin",
    capitalLocation: [-6.2603, 53.35],
    source: DEFAULT_SOURCE,
  },
  NC: {
    countryCode: "NC",
    capitalCity: "Noumea",
    capitalLocation: [166.458, -22.2758],
    source: DEFAULT_SOURCE,
  },
  SB: {
    countryCode: "SB",
    capitalCity: "Honiara",
    capitalLocation: [159.9556, -9.4319],
    source: DEFAULT_SOURCE,
  },
  NZ: {
    countryCode: "NZ",
    capitalCity: "Wellington",
    capitalLocation: [174.7772, -41.2889],
    source: DEFAULT_SOURCE,
  },
  AU: {
    countryCode: "AU",
    capitalCity: "Canberra",
    capitalLocation: [149.1269, -35.2931],
    source: DEFAULT_SOURCE,
  },
  LK: {
    countryCode: "LK",
    capitalCity: "Colombo",
    capitalLocation: [79.8428, 6.9344],
    source: DEFAULT_SOURCE,
  },
  CN: {
    countryCode: "CN",
    capitalCity: "Beijing",
    capitalLocation: [116.4075, 39.904],
    source: DEFAULT_SOURCE,
  },
  TW: {
    countryCode: "TW",
    capitalCity: "Taipei",
    capitalLocation: [121.5625, 25.0375],
    source: DEFAULT_SOURCE,
  },
  IT: {
    countryCode: "IT",
    capitalCity: "Rome",
    capitalLocation: [12.4828, 41.8931],
    source: DEFAULT_SOURCE,
  },
  DK: {
    countryCode: "DK",
    capitalCity: "Copenhagen",
    capitalLocation: [12.5683, 55.6761],
    source: DEFAULT_SOURCE,
  },
  GB: {
    countryCode: "GB",
    capitalCity: "London",
    capitalLocation: [-0.1275, 51.5072],
    source: DEFAULT_SOURCE,
  },
  IS: {
    countryCode: "IS",
    capitalCity: "Reykjavik",
    capitalLocation: [-21.94, 64.1467],
    source: DEFAULT_SOURCE,
  },
  AZ: {
    countryCode: "AZ",
    capitalCity: "Baku",
    capitalLocation: [49.8352, 40.3667],
    source: DEFAULT_SOURCE,
  },
  GE: {
    countryCode: "GE",
    capitalCity: "Tbilisi",
    capitalLocation: [44.7925, 41.7225],
    source: DEFAULT_SOURCE,
  },
  PH: {
    countryCode: "PH",
    capitalCity: "Manila",
    capitalLocation: [120.9772, 14.5958],
    source: DEFAULT_SOURCE,
  },
  MY: {
    countryCode: "MY",
    capitalCity: "Kuala Lumpur",
    capitalLocation: [101.6953, 3.1478],
    source: DEFAULT_SOURCE,
  },
  BN: {
    countryCode: "BN",
    capitalCity: "Bandar Seri Begawan",
    capitalLocation: [114.9422, 4.9167],
    source: DEFAULT_SOURCE,
  },
  SI: {
    countryCode: "SI",
    capitalCity: "Ljubljana",
    capitalLocation: [14.5061, 46.0514],
    source: DEFAULT_SOURCE,
  },
  FI: {
    countryCode: "FI",
    capitalCity: "Helsinki",
    capitalLocation: [24.9375, 60.1708],
    source: DEFAULT_SOURCE,
  },
  SK: {
    countryCode: "SK",
    capitalCity: "Bratislava",
    capitalLocation: [17.1097, 48.1439],
    source: DEFAULT_SOURCE,
  },
  CZ: {
    countryCode: "CZ",
    capitalCity: "Prague",
    capitalLocation: [14.4214, 50.0875],
    source: DEFAULT_SOURCE,
  },
  ER: {
    countryCode: "ER",
    capitalCity: "Asmara",
    capitalLocation: [38.925, 15.3228],
    source: DEFAULT_SOURCE,
  },
  JP: {
    countryCode: "JP",
    capitalCity: "Tokyo",
    capitalLocation: [139.6922, 35.6897],
    source: DEFAULT_SOURCE,
  },
  PY: {
    countryCode: "PY",
    capitalCity: "Asuncion",
    capitalLocation: [-57.6333, -25.3],
    source: DEFAULT_SOURCE,
  },
  YE: {
    countryCode: "YE",
    capitalCity: "Sanaa",
    capitalLocation: [44.2064, 15.3483],
    source: DEFAULT_SOURCE,
  },
  SA: {
    countryCode: "SA",
    capitalCity: "Riyadh",
    capitalLocation: [46.7167, 24.6333],
    source: DEFAULT_SOURCE,
  },
  CYP: {
    countryCode: "CYP",
    capitalCity: "Nicosia",
    capitalLocation: [33.3667, 35.1667],
    source: DEFAULT_SOURCE,
  },
  CY: {
    countryCode: "CY",
    capitalCity: "Nicosia",
    capitalLocation: [33.365, 35.1725],
    source: DEFAULT_SOURCE,
  },
  MA: {
    countryCode: "MA",
    capitalCity: "Rabat",
    capitalLocation: [-6.8416, 34.0209],
    source: DEFAULT_SOURCE,
  },
  EG: {
    countryCode: "EG",
    capitalCity: "Cairo",
    capitalLocation: [31.2358, 30.0444],
    source: DEFAULT_SOURCE,
  },
  LY: {
    countryCode: "LY",
    capitalCity: "Tripoli",
    capitalLocation: [13.1914, 32.8872],
    source: DEFAULT_SOURCE,
  },
  ET: {
    countryCode: "ET",
    capitalCity: "Addis Ababa",
    capitalLocation: [38.74, 9.03],
    source: DEFAULT_SOURCE,
  },
  DJ: {
    countryCode: "DJ",
    capitalCity: "Djibouti",
    capitalLocation: [43.145, 11.5883],
    source: DEFAULT_SOURCE,
  },
  SOM: {
    countryCode: "SOM",
    capitalCity: "Hargeisa",
    capitalLocation: [44.05, 9.56],
    source: DEFAULT_SOURCE,
  },
  UG: {
    countryCode: "UG",
    capitalCity: "Kampala",
    capitalLocation: [32.5811, 0.3136],
    source: DEFAULT_SOURCE,
  },
  RW: {
    countryCode: "RW",
    capitalCity: "Kigali",
    capitalLocation: [30.0606, -1.9536],
    source: DEFAULT_SOURCE,
  },
  BA: {
    countryCode: "BA",
    capitalCity: "Sarajevo",
    capitalLocation: [18.4131, 43.8564],
    source: DEFAULT_SOURCE,
  },
  MK: {
    countryCode: "MK",
    capitalCity: "Skopje",
    capitalLocation: [21.4317, 41.9961],
    source: DEFAULT_SOURCE,
  },
  RS: {
    countryCode: "RS",
    capitalCity: "Belgrade",
    capitalLocation: [20.46, 44.82],
    source: DEFAULT_SOURCE,
  },
  ME: {
    countryCode: "ME",
    capitalCity: "Podgorica",
    capitalLocation: [19.2629, 42.4413],
    source: DEFAULT_SOURCE,
  },
  XK: {
    countryCode: "XK",
    capitalCity: "Pristina",
    capitalLocation: [21.1622, 42.6633],
    source: DEFAULT_SOURCE,
  },
  TT: {
    countryCode: "TT",
    capitalCity: "Port of Spain",
    capitalLocation: [-61.5167, 10.6667],
    source: DEFAULT_SOURCE,
  },
  SS: {
    countryCode: "SS",
    capitalCity: "Juba",
    capitalLocation: [31.6, 4.85],
    source: DEFAULT_SOURCE,
  },
} satisfies Record<MapCountryCode, CountryCityMetadata>;

export function getCountryCityMetadata(
  countryCode: ISOCode,
): CountryCityMetadata | undefined {
  return countryCityMetadata[countryCode.toUpperCase() as MapCountryCode];
}
