/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access */
/**
 * One-time migration script: converts countries.geo.ts (abbreviated GeoJSON)
 * to a TopoJSON topology file (countries.topo.ts).
 *
 * Run with:  npx tsx scripts/migrate-to-topo.ts
 *
 * Why TopoJSON?
 *  - Shared borders between countries are stored only once (arc deduplication)
 *  - Coordinates are delta-encoded integers → much better gzip compression
 *  - The public API of react-svg-worldmap does not change at all
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { topology } from "topojson-server";
import geoData from "../src/countries.geo.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/* ── Build a proper GeoJSON FeatureCollection from the abbreviated data ── */

const featureCollection: GeoJSON.FeatureCollection = {
  type: "FeatureCollection",
  features: geoData.features.map(({ N, I, C }) => ({
    type: "Feature",
    properties: { N, I },
    geometry: {
      type: "MultiPolygon",
      // The stored coordinates are already in [lon, lat] pairs —
      // cast is safe because the shape matches GeoJSON.Position[][][].
      coordinates: C as unknown as GeoJSON.Position[][][],
    },
  })),
};

/* ── Convert to TopoJSON topology ── */

const topo = topology({ countries: featureCollection });

/* ── Emit countries.topo.ts ── */

const topoStr = JSON.stringify(topo);

const output = `/* prettier-ignore */
// AUTO-GENERATED by scripts/migrate-to-topo.ts — do not edit manually.
// Regenerate: npx tsx scripts/migrate-to-topo.ts

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const topoData: any = ${topoStr};

export default topoData;
`;

const outPath = resolve(__dirname, "../src/countries.topo.ts");
writeFileSync(outPath, output, "utf-8");

const bytes = Buffer.byteLength(output, "utf-8");
const original = Buffer.byteLength(JSON.stringify(geoData), "utf-8");
console.log(`✓  Written to src/countries.topo.ts`);
console.log(`   Original (approx): ${(original / 1024).toFixed(1)} KB`);
console.log(`   New:               ${(bytes / 1024).toFixed(1)} KB`);
console.log(
  `   Savings:           ${(((original - bytes) / original) * 100).toFixed(
    1,
  )}%`,
);
